---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Re-read facts after adding custom fact
      ansible.builtin.setup:
        filter: ansible_local

    - name: Check if resilio-sync service is running
      ansible.builtin.fail:
        msg: "resilio-sync service is not running"
      when: ((not ansible_local.rclone.installed | d()) | bool) 
